firstfile
sdlcorg/sdlcRepo pull request #2
Opened 2019-03-25 08:23 UTC by cttestid41

firstfile

2019-03-27 08:31 UTC, cttestid41 commented
first comment on pull request

2019-03-27 08:31 UTC, cttestid41 commented
second comment on pull request

2019-03-27 08:40 UTC, ravipatidar54 reviewed
This is my first review..................for comment

2019-03-27 08:41 UTC, ravipatidar54 reviewed
This is my first review..................for Request Change

2019-03-27 08:43 UTC, ravipatidar54 requested changes
This is my first review..................for Request change

2019-03-27 08:44 UTC, ravipatidar54 approved these changes
This is my first review..................for approved

2019-03-27 08:47 UTC, cttestid41 commented
asdlkfsak a;lskdjfl   lsadkjflas  ;alsdkfl asf ;llksad f

2019-07-25 05:44 UTC, cttestid41 commented
This is a comment on pull request

2025-02-17 10:17 UTC, merged